resolver: lts-12.21

packages:
- day1
- day2

extra-deps:
  - yaya-0.2.1.0
  - yaya-unsafe-0.1.1.0

ghc-options:
    # All packages
    "$locals":
      -Wall
      -Werror
      -fwarn-unused-imports
      -O2

