resolver: lts-12.21

packages:
- day1
- day2

extra-deps:
  - git: https://github.com/sellout/yaya
    commit: 0fadf0a4957dcce2d91888bef91a068b4e0f832b
    subdirs:
      - core
      - unsafe

ghc-options:
    # All packages
    "$locals":
      -Wall
      -Werror
      -fwarn-unused-imports
      -O2

