resolver: lts-12.21

packages:
- day1
- day2

extra-deps:
  - git: https://github.com/FintanH/yaya
    commit: dfb453270307fd5a8b2f846b5d5345a5156cb667
    subdirs:
      - core
      - unsafe

ghc-options:
    # All packages
    "$locals":
      -Wall
      -Werror
      -fwarn-unused-imports
      -O2

